"""
LLM 调用封装
LLM Call Wrapper
<p>
封装大语言模型调用逻辑，骨架阶段返回占位结果。
Wraps large language model call logic, returns placeholder results in skeleton phase.
</p>

@author DeltaTest
"""

from app.core.config import get_settings


class LLMService:
    """
    LLM 服务封装
    LLM Service Wrapper
    <p>
    骨架阶段仅定义接口，Phase 1 接入真实 LLM API。
    Skeleton phase only defines interfaces, Phase 1 integrates real LLM API.
    </p>
    """

    def __init__(self) -> None:
        """初始化 LLM 服务 / Initialize LLM service"""
        self._settings = get_settings()

    async def generate(self, prompt: str, system_prompt: str | None = None) -> str:
        """
        调用 LLM 生成文本
        Call LLM to generate text
        <p>
        骨架阶段返回占位文本，Phase 1 接入 OpenAI SDK。
        Returns placeholder text in skeleton phase, integrates OpenAI SDK in Phase 1.
        </p>

        Args:
            prompt: 用户提示词 / User prompt
            system_prompt: 系统提示词(可选) / System prompt (optional)

        Returns:
            str: LLM 生成的文本 / Text generated by LLM
        """
        # 骨架实现: 返回占位结果 / Skeleton implementation: return placeholder result
        _ = system_prompt  # 避免未使用参数警告 / Avoid unused parameter warning
        return f"[MOCK] LLM placeholder response for prompt: {prompt[:50]}..."


# 全局 LLM 服务实例 / Global LLM service instance
_llm_service: LLMService | None = None


def get_llm_service() -> LLMService:
    """
    获取 LLM 服务单例
    Get LLM service singleton

    Returns:
        LLMService: LLM 服务实例 / LLM service instance
    """
    global _llm_service
    if _llm_service is None:
        _llm_service = LLMService()
    return _llm_service
