package com.dwl.common.base;

import com.baomidou.mybatisplus.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * 基础实体类
 * Base Entity Class
 * <p>
 * 所有数据库实体的公共父类，包含主键ID、逻辑删除标识和审计时间字段。
 * Common parent class for all database entities, containing primary key ID,
 * logical delete flag, and audit timestamp fields.
 * </p>
 *
 * @author DeltaTest
 */
@Data
@Schema(description = "基础实体类 / Base Entity Class")
public abstract class BaseEntity implements Serializable {

    /**
     * 序列化版本号
     * Serial version UID
     */
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 主键ID（雪花算法生成）
     * Primary key ID (generated by snowflake algorithm)
     */
    @Schema(description = "主键ID / Primary key ID", example = "1234567890123456789")
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /**
     * 逻辑删除标识（0=未删除，1=已删除）
     * Logical delete flag (0=not deleted, 1=deleted)
     */
    @Schema(description = "逻辑删除标识 / Logical delete flag (0=normal, 1=deleted)", example = "0")
    @TableLogic
    private Integer isDeleted;

    /**
     * 创建时间（插入时自动填充）
     * Creation time (auto-filled on insert)
     */
    @Schema(description = "创建时间 / Creation time", example = "2025-01-01T00:00:00")
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;

    /**
     * 更新时间（插入和更新时自动填充）
     * Update time (auto-filled on insert and update)
     */
    @Schema(description = "更新时间 / Update time", example = "2025-01-01T00:00:00")
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;
}
