/**
 * 认证 API
 * Authentication API
 * <p>
 * 对接 Java 后端 /api/auth 接口，提供登录、刷新Token、退出登录。
 * Connects to Java backend /api/auth endpoints, providing login, refresh token, logout.
 * 类型定义由 openapi-typescript 从后端 OpenAPI spec 自动生成。
 * Type definitions are auto-generated by openapi-typescript from backend OpenAPI spec.
 * </p>
 *
 * @author ByDWL
 */
import type { components } from '@/api/types.generated'
import { post } from '@/utils/http'

/** 登录请求 DTO（从 OpenAPI 生成类型）/ Login Request DTO (from OpenAPI generated types) */
export type LoginDTO = components['schemas']['LoginDTO']

/** 登录响应 VO（从 OpenAPI 生成类型）/ Login Response VO (from OpenAPI generated types) */
export type LoginVO = components['schemas']['LoginVO']

/**
 * 用户登录
 * User login
 *
 * @param data 登录请求 / Login request
 * @returns 登录响应 / Login response
 */
export function loginApi(data: LoginDTO): Promise<LoginVO> {
  return post<LoginVO>('/api/auth/login', data)
}

/**
 * 刷新Token
 * Refresh token
 *
 * @param token 旧Token / Old token
 * @returns 新Token / New token
 */
export function refreshTokenApi(token: string): Promise<string> {
  return post<string>('/api/auth/refresh', null, {
    headers: { Authorization: `Bearer ${token}` },
  })
}

/**
 * 退出登录
 * Logout
 */
export function logoutApi(): Promise<void> {
  return post<void>('/api/auth/logout')
}
