/**
 * 健康检查 API
 * Health Check API
 * <p>
 * 对接 Java 后端 /api/health 接口，提供服务健康检查能力。
 * Connects to Java backend /api/health endpoint, providing service health check capability.
 * 类型定义由 openapi-typescript 从后端 OpenAPI spec 自动生成。
 * Type definitions are auto-generated by openapi-typescript from backend OpenAPI spec.
 * </p>
 *
 * @author ByDWL
 */
import type { components } from '@/api/types.generated'
import { get } from '@/utils/http'

/** 健康检查响应 VO（从 OpenAPI 生成类型）/ Health Check Response VO (from OpenAPI generated types) */
export type HealthVO = components['schemas']['HealthVO']

/**
 * 服务健康检查
 * Service health check
 * <p>
 * 检查后端服务是否正常运行，无需认证即可调用。
 * Checks if the backend service is running normally, no authentication required.
 * </p>
 *
 * @returns 健康检查响应 / Health check response
 */
export function healthCheckApi(): Promise<HealthVO> {
  return get<HealthVO>('/api/health')
}
