/**
 * API 模块统一导出
 * API Module Unified Exports
 * <p>
 * 所有 API 函数和类型的统一入口。类型定义由 openapi-typescript 自动生成。
 * Unified entry point for all API functions and types. Type definitions are auto-generated by openapi-typescript.
 * </p>
 *
 * 生成命令 / Generation command:
 *   pnpm api:generate        - 从运行中的后端生成 / Generate from running backend
 *   pnpm api:generate:local  - 从本地 OpenAPI spec 文件生成 / Generate from local OpenAPI spec file
 *
 * @author DeltaTest
 */
export { loginApi, refreshTokenApi, logoutApi } from './auth'
export type { LoginDTO, LoginVO } from './auth'

export { healthCheckApi } from './health'
export type { HealthVO } from './health'
