/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务健康检查 / Service health check
         * @description 检查服务是否正常运行 / Check if the service is running normally
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录 / User login
         * @description 用户名密码登录，返回JWT令牌 / Login with username and password, returns JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新Token / Refresh token
         * @description 使用旧Token获取新Token / Use old token to get new token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退出登录 / Logout
         * @description 退出登录，清除服务端会话 / Logout and clear server session
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 登录请求 / Login Request */
        LoginDTO: {
            /**
             * @description 用户名 / Username
             * @example admin
             */
            username: string;
            /**
             * @description 密码 / Password
             * @example 123456
             */
            password: string;
        };
        /** @description 登录响应 / Login Response */
        LoginVO: {
            /**
             * @description 访问令牌 / Access token
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token: string;
            /**
             * @description 令牌类型 / Token type
             * @example Bearer
             */
            tokenType: string;
            /**
             * Format: int64
             * @description 过期时间（秒）/ Expires in (seconds)
             * @example 86400
             */
            expiresIn: number;
            /**
             * Format: int64
             * @description 用户ID / User ID
             * @example 1
             */
            userId: number;
            /**
             * @description 用户名 / Username
             * @example admin
             */
            username: string;
            /**
             * @description 昵称 / Nickname
             * @example 管理员
             */
            nickname: string;
        };
        /** @description 健康检查响应 / Health Check Response */
        HealthVO: {
            /**
             * @description 服务状态 / Service status
             * @example UP
             */
            status: string;
            /**
             * @description 服务名称 / Service name
             * @example delta-test-server
             */
            service: string;
            /**
             * @description 版本号 / Version
             * @example 1.0.0-SNAPSHOT
             */
            version: string;
        };
        /** @description 统一响应体 / Unified response body */
        RVoid: {
            /**
             * @description 响应状态码 / Response status code
             * @example 200
             */
            code?: number;
            /**
             * @description 响应消息 / Response message
             * @example 操作成功
             */
            message?: string;
            data?: Record<string, never> | null;
            /**
             * Format: int64
             * @description 响应时间戳 / Response timestamp
             */
            timestamp?: number;
        };
        /** @description 统一响应体(String) / Unified response body (String) */
        RString: {
            /** @example 200 */
            code?: number;
            /** @example 操作成功 */
            message?: string;
            data?: string | null;
            /** Format: int64 */
            timestamp?: number;
        };
        /** @description 统一响应体(LoginVO) / Unified response body (LoginVO) */
        RLoginVO: {
            /** @example 200 */
            code?: number;
            /** @example 操作成功 */
            message?: string;
            data?: components["schemas"]["LoginVO"];
            /** Format: int64 */
            timestamp?: number;
        };
        /** @description 统一响应体(HealthVO) / Unified response body (HealthVO) */
        RHealthVO: {
            /** @example 200 */
            code?: number;
            /** @example 操作成功 */
            message?: string;
            data?: components["schemas"]["HealthVO"];
            /** Format: int64 */
            timestamp?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 健康检查响应 / Health check response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RHealthVO"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description 登录成功 / Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RLoginVO"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer Token */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新成功 / Refresh successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RString"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退出成功 / Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RVoid"];
                };
            };
        };
    };
}
